-- https://www.hackerrank.com/challenges/challenges/problem
-- Challenges

SET @TOP_CHLG_CNT := 
(SELECT MAX(C.CHLG_CNT)
FROM (SELECT COUNT(CHALLENGE_ID) CHLG_CNT
      FROM CHALLENGES
      GROUP BY HACKER_ID) C
);
SELECT HC.HACKER_ID, H.NAME, CNT.CHLG_CNT
FROM (
    SELECT CHLG_CNT
    FROM (
        SELECT COUNT(CHALLENGE_ID) CHLG_CNT
        FROM CHALLENGES
        GROUP BY HACKER_ID) C
    GROUP BY CHLG_CNT
    HAVING CHLG_CNT = @TOP_CHLG_CNT
    OR COUNT(CHLG_CNT) = 1
) CNT 
LEFT JOIN (
    SELECT HACKER_ID, COUNT(CHALLENGE_ID) CHLG_CNT
    FROM CHALLENGES
    GROUP BY HACKER_ID
) HC ON HC.CHLG_CNT = CNT.CHLG_CNT
JOIN HACKERS H ON HC.HACKER_ID = H.HACKER_ID
ORDER BY CHLG_CNT DESC, HACKER_ID;
